### PR TITLE
Add Everyday logo

### PR DESCRIPTION
**Pull request by rebekaburnett**

### CODE REVIEW

**Review by tomas-zijdemans-vipps — APPROVED** [review]

**Comment by Marcuzz** [comment]
I did not mean to mark it as ready for review, but I think it looks good. Just tell me when it's ready to be merged 😊

**Comment by rebekaburnett** [comment]
Hi @Marcuzz! No worries! I needed to merge the code in our Docusaurus repo before I could merge this, but we can merge it now.

**Comment by Marcuzz** [comment]
@rebekaburnett Unfortunately it looks like the dark mode/light mode images don't like being wrapped in a link 😢

**Comment by rebekaburnett** [comment]
@Marcuzz I will remove that link asap.

**Pull request merged**
